### ISSUE TITLE
KnotClassLoader class package change (NoClassDefFoundError)

### ISSUE THREAD

**Issue by sylv256** [Devan-Kerman/GrossFabricHacks#13]

**Comment by sylv256** [comment]
@auoeke @Devan-Kerman Please contact me on Discord if you can. I'd love to maintain this mod and keep it alive! `Sylv#1337`

**Comment by nnym** [comment]
GrossFabricHacks' public license allows you to fork, modify and distribute it. You could also check out the forks that some people have made.

**Comment by sylv256** [comment]
Is this project no longer being maintained?

**Comment by nnym** [comment]
I (and [I suppose Devan](https://github.com/Devan-Kerman/GrossFabricHacks/pull/12#issuecomment-898798308)) don't maintain it but some forks look potentially up to date.

**Comment by Ueaj-Kerman** [comment]
yeah I don't intend on maintaining it, atleast not for the foreseeable future. You're free & welcome to do it yourself though.
